from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from .config import Settings
from .obsidian import ObsidianWriter, REVIEWED_STATUSES
from .textutil import yaml_scalar
from .timeutil import now_local
from .vault_index import _frontmatter_scalar, _markdown_files, _set_frontmatter_scalars, _split_frontmatter


RUN_CLEANUP_CHECK_RE = re.compile(r"^- \[(?P<state>[ xX])\]\s+(?P<proposal_id>A\d{3})\b", re.MULTILINE)
CANDIDATE_BLOCK_RE = re.compile(r"## Candidate Records\s*```json\s*(?P<json>[\s\S]*?)\s*```", re.MULTILINE)
AUDIT_TYPES = {"source-audit", "bilingual-audit"}
ARCHIVABLE_PROPOSAL_STATES = {"applied", "superseded"}
SNAPSHOT_TYPES = {"next-actions", "vault-health"}


@dataclass(frozen=True)
class RunCleanupCandidate:
    proposal_id: str
    path: Path
    relative_path: str
    note_type: str
    status: str
    checked_at: str
    proposal_state: str
    reason: str


@dataclass(frozen=True)
class RunCleanupSkippedItem:
    path: Path
    relative_path: str
    note_type: str
    status: str
    reason: str


@dataclass(frozen=True)
class RunCleanupResult:
    vault_path: Path
    run_notes_scanned: int
    candidates: list[RunCleanupCandidate]
    skipped_items: list[RunCleanupSkippedItem]


@dataclass(frozen=True)
class RunCleanupWriteResult:
    result: RunCleanupResult
    note_path: Path


@dataclass(frozen=True)
class RunCleanupApplyItem:
    proposal_path: Path
    proposal_id: str
    path: Path
    relative_path: str
    reason: str


@dataclass(frozen=True)
class RunCleanupApplyResult:
    dry_run: bool
    proposal_notes: int
    approved_items: list[RunCleanupApplyItem]
    updated_paths: list[Path]
    skipped_items: list[RunCleanupSkippedItem]


@dataclass(frozen=True)
class RunCleanupQueue:
    proposal_paths: list[Path]
    pending_candidates: int
    checked_items: int
    checked_proposal_paths: list[Path]


@dataclass(frozen=True)
class _RunNote:
    path: Path
    relative_path: str
    note_type: str
    status: str
    checked_at: str
    proposal_state: str
    audit_status: str
    failure_count: int
    warning_count: int


def build_run_cleanup(settings: Settings, *, max_proposals: int = 100) -> RunCleanupResult:
    vault = settings.obsidian.vault_path.expanduser().resolve()
    run_dir = settings.obsidian.run_dir.strip().strip("/")
    notes: list[_RunNote] = []
    skipped_items: list[RunCleanupSkippedItem] = []

    for path in sorted(_markdown_files(vault / run_dir), key=lambda item: item.relative_to(vault).as_posix()):
        text = path.read_text(encoding="utf-8", errors="replace")
        frontmatter, _body = _split_frontmatter(text)
        note = _run_note(path, vault=vault, frontmatter=frontmatter)
        if _frontmatter_scalar(frontmatter, "generated_by") != "research-agent":
            skipped_items.append(_skip_from_note(note, "not generated by research-agent"))
            continue
        if note.status.lower() == "archived":
            skipped_items.append(_skip_from_note(note, "already archived"))
            continue
        if note.status.lower() in REVIEWED_STATUSES:
            skipped_items.append(_skip_from_note(note, "protected reviewed/evergreen run note"))
            continue
        notes.append(note)

    candidates = _archive_candidates(notes)
    limited_candidates = candidates[:max_proposals]
    return RunCleanupResult(
        vault_path=vault,
        run_notes_scanned=len(notes),
        candidates=[
            RunCleanupCandidate(
                proposal_id=f"A{index + 1:03d}",
                path=candidate.path,
                relative_path=candidate.relative_path,
                note_type=candidate.note_type,
                status=candidate.status,
                checked_at=candidate.checked_at,
                proposal_state=candidate.proposal_state,
                reason=reason,
            )
            for index, (candidate, reason) in enumerate(limited_candidates)
        ],
        skipped_items=skipped_items,
    )


def build_run_cleanup_queue(vault_path: Path) -> RunCleanupQueue:
    vault = vault_path.expanduser().resolve()
    proposal_paths: list[Path] = []
    pending_candidates = 0
    checked_items = 0
    checked_proposal_paths: list[Path] = []

    for proposal_path in _run_cleanup_notes(vault):
        text = proposal_path.read_text(encoding="utf-8", errors="replace")
        frontmatter, _body = _split_frontmatter(text)
        if _frontmatter_scalar(frontmatter, "proposal_state").lower() == "applied":
            continue
        records = _candidate_records(text, vault=vault)
        checked_ids = _checked_proposal_ids(text)
        if not records and not checked_ids:
            continue
        proposal_paths.append(proposal_path)
        pending_candidates += len(records)
        checked_items += len(checked_ids)
        if checked_ids:
            checked_proposal_paths.append(proposal_path)

    return RunCleanupQueue(
        proposal_paths=proposal_paths,
        pending_candidates=pending_candidates,
        checked_items=checked_items,
        checked_proposal_paths=checked_proposal_paths,
    )


def render_run_cleanup(result: RunCleanupResult, *, max_proposals: int = 100, max_skipped: int = 50) -> str:
    shown = result.candidates[:max_proposals]
    hidden = len(result.candidates) - len(shown)
    shown_skipped = result.skipped_items[:max_skipped]
    hidden_skipped = len(result.skipped_items) - len(shown_skipped)
    return f"""Run Cleanup Proposals

Vault: {result.vault_path}
Generated run notes scanned: {result.run_notes_scanned}
Archive candidates: {len(result.candidates)}
Skipped notes: {len(result.skipped_items)}

Proposals:
{_proposal_lines(shown)}
{_hidden_line(hidden, max_proposals)}

Skipped:
{_skipped_lines(shown_skipped)}
{_hidden_skipped_line(hidden_skipped, max_skipped)}
"""


def write_run_cleanup_note(settings: Settings, *, max_proposals: int = 100) -> RunCleanupWriteResult:
    result = build_run_cleanup(settings, max_proposals=max_proposals)
    timestamp = now_local(settings.app.timezone)
    writer = ObsidianWriter(
        settings.obsidian,
        common_module_path=settings.common.module_path,
        use_common_module=settings.common.enabled,
    )
    writer.ensure_structure()
    path = writer.write_note(
        settings.obsidian.run_dir,
        f"{timestamp.date().isoformat()}_run-cleanup.md",
        render_run_cleanup_note(result, checked_at=timestamp.isoformat(timespec="seconds"), max_proposals=max_proposals),
    )
    return RunCleanupWriteResult(result=result, note_path=path)


def apply_run_cleanup(settings: Settings, *, dry_run: bool = True, archived_at: str = "") -> RunCleanupApplyResult:
    vault = settings.obsidian.vault_path.expanduser().resolve()
    proposal_notes = 0
    approved_items: list[RunCleanupApplyItem] = []
    updated_paths: list[Path] = []
    skipped_items: list[RunCleanupSkippedItem] = []
    proposal_paths_to_mark: set[Path] = set()

    for proposal_path in _run_cleanup_notes(vault):
        proposal_notes += 1
        text = proposal_path.read_text(encoding="utf-8", errors="replace")
        records = _candidate_records(text, vault=vault)
        checked_ids = _checked_proposal_ids(text)
        for proposal_id in checked_ids:
            candidate = records.get(proposal_id)
            if candidate is None:
                skipped_items.append(RunCleanupSkippedItem(proposal_path, proposal_path.relative_to(vault).as_posix(), "run-cleanup", "", "candidate record not found"))
                continue
            if not candidate.path.exists():
                skipped_items.append(_skip_from_candidate(candidate, "run note not found"))
                continue
            current_text = candidate.path.read_text(encoding="utf-8", errors="replace")
            frontmatter, _body = _split_frontmatter(current_text)
            status = _frontmatter_scalar(frontmatter, "status")
            if status.lower() == "archived":
                skipped_items.append(_skip_from_candidate(candidate, "already archived"))
                continue
            if status.lower() in REVIEWED_STATUSES:
                skipped_items.append(_skip_from_candidate(candidate, "protected reviewed/evergreen run note"))
                continue
            values = {
                "status": "archived",
                "archived_by": "research-agent",
                "archive_reason": candidate.reason,
            }
            if archived_at:
                values["archived_at"] = archived_at
            updated = _set_frontmatter_scalars(current_text, values)
            if not dry_run:
                candidate.path.write_text(updated, encoding="utf-8")
            approved_items.append(
                RunCleanupApplyItem(
                    proposal_path=proposal_path,
                    proposal_id=proposal_id,
                    path=candidate.path,
                    relative_path=candidate.relative_path,
                    reason=candidate.reason,
                )
            )
            updated_paths.append(candidate.path)
            proposal_paths_to_mark.add(proposal_path)

    if not dry_run:
        for proposal_path in proposal_paths_to_mark:
            text = proposal_path.read_text(encoding="utf-8", errors="replace")
            values = {"proposal_state": "applied"}
            if archived_at:
                values["applied_at"] = archived_at
            proposal_path.write_text(_set_frontmatter_scalars(text, values), encoding="utf-8")

    return RunCleanupApplyResult(
        dry_run=dry_run,
        proposal_notes=proposal_notes,
        approved_items=approved_items,
        updated_paths=sorted(set(updated_paths), key=lambda item: item.as_posix()),
        skipped_items=skipped_items,
    )


def render_run_cleanup_apply_result(result: RunCleanupApplyResult) -> str:
    title = "Run Cleanup Apply Dry Run" if result.dry_run else "Run Cleanup Apply"
    action = "Would archive notes" if result.dry_run else "Archived notes"
    return f"""{title}

Proposal notes scanned: {result.proposal_notes}
Approved checklist items: {len(result.approved_items)}
{action}: {len(result.updated_paths)}
Skipped items: {len(result.skipped_items)}

Approved items:
{_apply_item_lines(result.approved_items)}

Updated notes:
{_path_lines(result.updated_paths)}

Skipped items:
{_skipped_lines(result.skipped_items)}
"""


def render_run_cleanup_note(
    result: RunCleanupResult,
    *,
    checked_at: str,
    max_proposals: int = 100,
) -> str:
    shown = result.candidates[:max_proposals]
    hidden = len(result.candidates) - len(shown)
    return f"""---
type: {yaml_scalar("run-cleanup")}
status: {yaml_scalar("draft")}
proposal_state: {yaml_scalar("proposed")}
generated_by: {yaml_scalar("research-agent")}
checked_at: {yaml_scalar(checked_at)}
notes_scanned: {result.run_notes_scanned}
proposal_count: {len(result.candidates)}
skipped_count: {len(result.skipped_items)}
---
# Run Cleanup

## Summary

| metric | value |
|---|---:|
| generated run notes scanned | {result.run_notes_scanned} |
| archive candidates | {len(result.candidates)} |
| skipped notes | {len(result.skipped_items)} |

## Proposals

{_proposal_lines(shown)}
{_hidden_line(hidden, max_proposals)}

## Skipped

{_skipped_lines(result.skipped_items)}

## Review Checklist

- [ ] Confirm these run notes are completed history, not active work.
- [ ] Apply accepted archive status updates with `apply-run-cleanup`.
- [ ] Rerun `index-vault`.

## Candidate Records

```json
{_candidate_json(result.candidates)}
```
"""


def _archive_candidates(notes: list[_RunNote]) -> list[tuple[_RunNote, str]]:
    candidates: list[tuple[_RunNote, str]] = []
    seen: set[Path] = set()

    for note in notes:
        state = note.proposal_state.lower()
        if note.note_type != "run-cleanup" and state in ARCHIVABLE_PROPOSAL_STATES:
            candidates.append((note, f"completed proposal lifecycle: {state}"))
            seen.add(note.path)

    clean_audits_by_type: dict[str, list[_RunNote]] = {}
    for note in notes:
        if note.note_type in AUDIT_TYPES and _is_clean_pass_audit(note):
            clean_audits_by_type.setdefault(note.note_type, []).append(note)

    for note_type, audit_notes in clean_audits_by_type.items():
        ordered = sorted(audit_notes, key=_run_note_sort_key)
        latest = ordered[-1] if ordered else None
        for note in ordered[:-1]:
            if note.path in seen:
                continue
            latest_path = latest.relative_path if latest else f"latest {note_type}"
            candidates.append((note, f"superseded by newer clean {note_type}: {latest_path}"))
            seen.add(note.path)

    snapshots_by_type: dict[str, list[_RunNote]] = {}
    for note in notes:
        if note.note_type in SNAPSHOT_TYPES:
            snapshots_by_type.setdefault(note.note_type, []).append(note)

    for note_type, snapshot_notes in snapshots_by_type.items():
        ordered = sorted(snapshot_notes, key=_run_note_sort_key)
        latest = ordered[-1] if ordered else None
        for note in ordered[:-1]:
            if note.path in seen:
                continue
            latest_path = latest.relative_path if latest else f"latest {note_type}"
            candidates.append((note, f"superseded by newer {note_type} snapshot: {latest_path}"))
            seen.add(note.path)

    return sorted(candidates, key=lambda item: item[0].relative_path)


def _run_note(path: Path, *, vault: Path, frontmatter: dict[str, str | list[str]]) -> _RunNote:
    return _RunNote(
        path=path,
        relative_path=path.relative_to(vault).as_posix(),
        note_type=_frontmatter_scalar(frontmatter, "type") or "unknown",
        status=_frontmatter_scalar(frontmatter, "status") or "missing",
        checked_at=_frontmatter_scalar(frontmatter, "checked_at") or _frontmatter_scalar(frontmatter, "created_at"),
        proposal_state=_frontmatter_scalar(frontmatter, "proposal_state"),
        audit_status=_frontmatter_scalar(frontmatter, "audit_status"),
        failure_count=_frontmatter_int(frontmatter, "failure_count"),
        warning_count=_frontmatter_int(frontmatter, "warning_count"),
    )


def _is_clean_pass_audit(note: _RunNote) -> bool:
    return note.audit_status.upper() == "PASS" and note.failure_count == 0 and note.warning_count == 0


def _frontmatter_int(frontmatter: dict[str, str | list[str]], key: str) -> int:
    value = _frontmatter_scalar(frontmatter, key)
    try:
        return int(value)
    except ValueError:
        return 0


def _run_note_sort_key(note: _RunNote) -> tuple[str, str]:
    return note.checked_at, note.relative_path


def _candidate_json(candidates: list[RunCleanupCandidate]) -> str:
    return json.dumps([_candidate_to_json(candidate) for candidate in candidates], ensure_ascii=False, indent=2)


def _candidate_to_json(candidate: RunCleanupCandidate) -> dict:
    return {
        "proposal_id": candidate.proposal_id,
        "path": candidate.relative_path,
        "note_type": candidate.note_type,
        "status": candidate.status,
        "checked_at": candidate.checked_at,
        "proposal_state": candidate.proposal_state,
        "reason": candidate.reason,
    }


def _candidate_records(text: str, *, vault: Path) -> dict[str, RunCleanupCandidate]:
    match = CANDIDATE_BLOCK_RE.search(text)
    if not match:
        return {}
    try:
        items = json.loads(match.group("json"))
    except json.JSONDecodeError:
        return {}
    if not isinstance(items, list):
        return {}
    records: dict[str, RunCleanupCandidate] = {}
    for item in items:
        if not isinstance(item, dict):
            continue
        candidate = _candidate_from_json(item, vault=vault)
        if candidate:
            records[candidate.proposal_id] = candidate
    return records


def _candidate_from_json(item: dict, *, vault: Path) -> RunCleanupCandidate | None:
    proposal_id = str(item.get("proposal_id") or "").strip()
    relative_path = str(item.get("path") or "").strip()
    path = _vault_path(vault, relative_path)
    note_type = str(item.get("note_type") or "").strip()
    reason = str(item.get("reason") or "").strip()
    if not proposal_id or path is None or not note_type or not reason:
        return None
    return RunCleanupCandidate(
        proposal_id=proposal_id,
        path=path,
        relative_path=relative_path,
        note_type=note_type,
        status=str(item.get("status") or "").strip(),
        checked_at=str(item.get("checked_at") or "").strip(),
        proposal_state=str(item.get("proposal_state") or "").strip(),
        reason=reason,
    )


def _checked_proposal_ids(text: str) -> list[str]:
    return [match.group("proposal_id") for match in RUN_CLEANUP_CHECK_RE.finditer(text) if match.group("state").strip().lower() == "x"]


def _run_cleanup_notes(vault: Path) -> list[Path]:
    paths: list[Path] = []
    for path in _markdown_files(vault):
        text = path.read_text(encoding="utf-8", errors="replace")
        frontmatter, _body = _split_frontmatter(text)
        if _frontmatter_scalar(frontmatter, "type") == "run-cleanup":
            paths.append(path)
    return sorted(paths)


def _proposal_lines(candidates: list[RunCleanupCandidate]) -> str:
    if not candidates:
        return "- None."
    return "\n".join(_proposal_line(candidate) for candidate in candidates)


def _proposal_line(candidate: RunCleanupCandidate) -> str:
    return f"- [ ] {candidate.proposal_id} Archive [{candidate.relative_path}]({candidate.relative_path}) ({candidate.note_type}, status: {candidate.status}); reason: {candidate.reason}"


def _apply_item_lines(items: list[RunCleanupApplyItem]) -> str:
    if not items:
        return "- None."
    return "\n".join(f"- {item.proposal_id} {item.relative_path}: {item.reason}" for item in items)


def _skipped_lines(items: list[RunCleanupSkippedItem]) -> str:
    if not items:
        return "- None."
    return "\n".join(f"- {item.relative_path} ({item.note_type}, status: {item.status or 'unknown'}): {item.reason}" for item in items)


def _path_lines(paths: list[Path]) -> str:
    if not paths:
        return "- None."
    return "\n".join(f"- {path}" for path in paths)


def _hidden_line(hidden: int, max_proposals: int) -> str:
    if hidden <= 0:
        return ""
    return f"\n... {hidden} more proposal(s) hidden by --max-proposals={max_proposals}."


def _hidden_skipped_line(hidden: int, max_skipped: int) -> str:
    if hidden <= 0:
        return ""
    return f"\n... {hidden} more skipped note(s) hidden by --max-skipped={max_skipped}."


def _skip_from_note(note: _RunNote, reason: str) -> RunCleanupSkippedItem:
    return RunCleanupSkippedItem(
        path=note.path,
        relative_path=note.relative_path,
        note_type=note.note_type,
        status=note.status,
        reason=reason,
    )


def _skip_from_candidate(candidate: RunCleanupCandidate, reason: str) -> RunCleanupSkippedItem:
    return RunCleanupSkippedItem(
        path=candidate.path,
        relative_path=candidate.relative_path,
        note_type=candidate.note_type,
        status=candidate.status,
        reason=reason,
    )


def _vault_path(vault: Path, relative: str) -> Path | None:
    clean = relative.strip().strip("/")
    if not clean:
        return None
    candidate = (vault / clean).resolve()
    if candidate != vault and vault not in candidate.parents:
        return None
    return candidate
